name: raspberry-pi-project
app: dockerfile
options:
  ports: 8000
  dockerfile: Dockerfile
  shell: /bin/bash
context:
  git:
    url: https://github.com/ikk5515/raspberry-pi-project.git
    branch: main
  preset: dockerfile
