name: raspberry-pi-project
app: python@3.9
resources:
  cpu: 1
  memory: 1
options:
  ports: 8000
  start: uvicorn main:app --host=0.0.0.0 --port=8000
  nodeversion: "14"
  install: |
    sudo apt-get update
    sudo apt-get install -y pkg-config
    pip install -r requirements.txt
context:
  git:
    url: git@github.com:ikk5515/raspberry-pi-project.git
    ref: refs/heads/main
    path: Back
    branch: main
