name: raspberry-pi-project
app: python@3.9
options:
  ports: 8000
  start: uvicorn main:app --host=0.0.0.0 --port=8000
context:
  git:
    url: https://github.com/ikk5515/raspberry-pi-project.git
    branch: main
    subdirectory: Back
