name: raspberry-pi-project
app: python@3.9
options:
  ports: 8000
  start: uvicorn main:app --host=0.0.0.0 --port=8000
  nodeversion: "14"
  env:
    - name: DATABASE_URL
      secret: .env2
context:
  git:
    url: git@github.com:ikk5515/raspberry-pi-project.git
    ref: refs/heads/main
    path: Back
