name: raspberry-pi-project
app: dockerfile
options:
  ports: 8000
  dockerfile: Dockerfile
  shell: /bin/zsh
context:
  git:
    url: git@github.com:ikk5515/raspberry-pi-project.git
    ref: refs/heads/main
    branch: main
    path: "Back"
  preset: dockerfile
