name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config
          pip install -r requirements.txt
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ikk5515/raspberry-pi-project
          stage: main
          yaml: |
            name: raspberry-pi-project
            app: python@3.9
            options:
              ports: 8000
              start: uvicorn main:app --host=0.0.0.0 --port=8000
              nodeversion: "14"
              install: |
                RUN apt-get update
                RUN apt-get install -y pkg-config
                RUN pip install -r requirements.txt
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
                path: Back
