name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config
          sudo apt-get install -y libmysqlclient-dev  # Add this line for mysqlclient dependencies

      - name: Install Python dependencies
        run: |
          if [ -f "./requirements.txt" ]; then
            pip install -r requirements.txt
          fi
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ikk5515/raspberry-pi-project
          stage: main
          yaml: |
            name: raspberry-pi-project
            app: dockerfile
            options:
              ports: 8000
              dockerfile: Dockerfile
              shell: /bin/bash
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: dockerfile
